"""Download vendored web assets (Three.js, web fonts) from the npm registry.

This script is called automatically from setup.py during ``colcon build`` /
``pip install``.  Internet access is required at build time; the downloaded
files are written to ``web/vendor/`` and served locally at runtime so the
viewer works without any internet connection.

The script is idempotent: it skips individual files that already exist, so
repeated builds are fast.  Delete ``web/vendor/`` to force a full re-download.
"""

import io
import logging
import os
import tarfile
import urllib.error
import urllib.request

log = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Version pins
# ---------------------------------------------------------------------------
THREE_VERSION = '0.161.0'

FONTSOURCE_VERSIONS = {
    'playfair-display': '5.2.8',
    'lato': '5.2.7',
    'ibm-plex-mono': '5.2.7',
}

# ---------------------------------------------------------------------------
# Three.js files to extract from the npm tarball
# (archive path inside tarball  →  destination relative to vendor/three/)
# ---------------------------------------------------------------------------
THREE_FILES = {
    'package/build/three.module.js': 'three.module.js',
    'package/examples/jsm/controls/OrbitControls.js': 'addons/controls/OrbitControls.js',
    'package/examples/jsm/loaders/STLLoader.js': 'addons/loaders/STLLoader.js',
    'package/examples/jsm/loaders/ColladaLoader.js': 'addons/loaders/ColladaLoader.js',
    # ColladaLoader depends on TGALoader via relative import
    'package/examples/jsm/loaders/TGALoader.js': 'addons/loaders/TGALoader.js',
}

# ---------------------------------------------------------------------------
# Font files to extract from each @fontsource npm tarball
# (archive member suffix  →  destination filename under vendor/fonts/files/)
# The full archive path is  package/files/<filename>
# ---------------------------------------------------------------------------
FONT_FILES = {
    'playfair-display': [
        'playfair-display-latin-400-normal.woff2',
        'playfair-display-latin-400-normal.woff',
        'playfair-display-latin-700-normal.woff2',
        'playfair-display-latin-700-normal.woff',
        'playfair-display-latin-400-italic.woff2',
        'playfair-display-latin-400-italic.woff',
    ],
    'lato': [
        'lato-latin-300-normal.woff2',
        'lato-latin-300-normal.woff',
        'lato-latin-400-normal.woff2',
        'lato-latin-400-normal.woff',
        'lato-latin-700-normal.woff2',
        'lato-latin-700-normal.woff',
    ],
    'ibm-plex-mono': [
        'ibm-plex-mono-latin-300-normal.woff2',
        'ibm-plex-mono-latin-300-normal.woff',
        'ibm-plex-mono-latin-400-normal.woff2',
        'ibm-plex-mono-latin-400-normal.woff',
        'ibm-plex-mono-latin-500-normal.woff2',
        'ibm-plex-mono-latin-500-normal.woff',
    ],
}

# Generated fonts.css content (paths are relative to vendor/fonts/)
_FONTS_CSS = """\
/* Vendored web fonts — generated by download_web_assets.py */

/* Playfair Display */
@font-face {
  font-family: 'Playfair Display';
  font-style: normal;
  font-display: swap;
  font-weight: 400;
  src: url(./files/playfair-display-latin-400-normal.woff2) format('woff2'),
       url(./files/playfair-display-latin-400-normal.woff) format('woff');
}
@font-face {
  font-family: 'Playfair Display';
  font-style: normal;
  font-display: swap;
  font-weight: 700;
  src: url(./files/playfair-display-latin-700-normal.woff2) format('woff2'),
       url(./files/playfair-display-latin-700-normal.woff) format('woff');
}
@font-face {
  font-family: 'Playfair Display';
  font-style: italic;
  font-display: swap;
  font-weight: 400;
  src: url(./files/playfair-display-latin-400-italic.woff2) format('woff2'),
       url(./files/playfair-display-latin-400-italic.woff) format('woff');
}

/* Lato */
@font-face {
  font-family: 'Lato';
  font-style: normal;
  font-display: swap;
  font-weight: 300;
  src: url(./files/lato-latin-300-normal.woff2) format('woff2'),
       url(./files/lato-latin-300-normal.woff) format('woff');
}
@font-face {
  font-family: 'Lato';
  font-style: normal;
  font-display: swap;
  font-weight: 400;
  src: url(./files/lato-latin-400-normal.woff2) format('woff2'),
       url(./files/lato-latin-400-normal.woff) format('woff');
}
@font-face {
  font-family: 'Lato';
  font-style: normal;
  font-display: swap;
  font-weight: 700;
  src: url(./files/lato-latin-700-normal.woff2) format('woff2'),
       url(./files/lato-latin-700-normal.woff) format('woff');
}

/* IBM Plex Mono */
@font-face {
  font-family: 'IBM Plex Mono';
  font-style: normal;
  font-display: swap;
  font-weight: 300;
  src: url(./files/ibm-plex-mono-latin-300-normal.woff2) format('woff2'),
       url(./files/ibm-plex-mono-latin-300-normal.woff) format('woff');
}
@font-face {
  font-family: 'IBM Plex Mono';
  font-style: normal;
  font-display: swap;
  font-weight: 400;
  src: url(./files/ibm-plex-mono-latin-400-normal.woff2) format('woff2'),
       url(./files/ibm-plex-mono-latin-400-normal.woff) format('woff');
}
@font-face {
  font-family: 'IBM Plex Mono';
  font-style: normal;
  font-display: swap;
  font-weight: 500;
  src: url(./files/ibm-plex-mono-latin-500-normal.woff2) format('woff2'),
       url(./files/ibm-plex-mono-latin-500-normal.woff) format('woff');
}
"""


def _npm_tarball_url(package: str, version: str) -> str:
    """Return the npm registry tarball URL for a given package and version."""
    # Scoped packages like @fontsource/lato use %2F encoding in the URL.
    encoded = package.replace('/', '%2F').replace('@', '%40')
    return f'https://registry.npmjs.org/{encoded}/-/{package.split("/")[-1]}-{version}.tgz'


def _fetch_tarball(url: str) -> tarfile.TarFile:
    """Download a .tgz from *url* and return it as an in-memory TarFile."""
    log.info('Downloading %s', url)
    with urllib.request.urlopen(url, timeout=60) as response:
        data = response.read()
    return tarfile.open(fileobj=io.BytesIO(data), mode='r:gz')


def _extract_member(tf: tarfile.TarFile, member_path: str, dest: str) -> None:
    """Extract one file from *tf* to *dest*, creating parent dirs as needed."""
    os.makedirs(os.path.dirname(dest), exist_ok=True)
    try:
        member = tf.getmember(member_path)
    except KeyError:
        raise FileNotFoundError(
            f'Expected member {member_path!r} not found in tarball'
        )
    with tf.extractfile(member) as src, open(dest, 'wb') as dst:
        dst.write(src.read())


def download_web_assets(web_dir=None):
    # type: (str | None) -> None
    """Download all vendored web assets into *web_dir*/vendor/.

    *web_dir* defaults to the ``web/`` directory next to this script.
    """
    if web_dir is None:
        web_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'web')

    vendor_dir = os.path.join(web_dir, 'vendor')

    # -----------------------------------------------------------------------
    # Three.js
    # -----------------------------------------------------------------------
    three_dir = os.path.join(vendor_dir, 'three')
    missing_three = [
        arc for arc, rel in THREE_FILES.items()
        if not os.path.exists(os.path.join(three_dir, rel))
    ]

    if missing_three:
        url = _npm_tarball_url('three', THREE_VERSION)
        tf = _fetch_tarball(url)
        for arc_path, rel_dest in THREE_FILES.items():
            dest = os.path.join(three_dir, rel_dest)
            if not os.path.exists(dest):
                _extract_member(tf, arc_path, dest)
                log.info('Installed %s', dest)
        tf.close()
    else:
        log.info('Three.js v%s already present, skipping download', THREE_VERSION)

    # -----------------------------------------------------------------------
    # Web fonts (@fontsource packages)
    # -----------------------------------------------------------------------
    fonts_dir = os.path.join(vendor_dir, 'fonts')
    fonts_files_dir = os.path.join(fonts_dir, 'files')

    for pkg_short, version in FONTSOURCE_VERSIONS.items():
        filenames = FONT_FILES[pkg_short]
        missing = [f for f in filenames if not os.path.exists(os.path.join(fonts_files_dir, f))]
        if not missing:
            log.info('@fontsource/%s already present, skipping download', pkg_short)
            continue

        url = _npm_tarball_url(f'@fontsource/{pkg_short}', version)
        tf = _fetch_tarball(url)
        for filename in filenames:
            dest = os.path.join(fonts_files_dir, filename)
            if not os.path.exists(dest):
                _extract_member(tf, f'package/files/{filename}', dest)
                log.info('Installed %s', dest)
        tf.close()

    # Write the generated fonts.css (always regenerate to keep it up to date).
    fonts_css_path = os.path.join(fonts_dir, 'fonts.css')
    os.makedirs(fonts_dir, exist_ok=True)
    with open(fonts_css_path, 'w', encoding='utf-8') as f:
        f.write(_FONTS_CSS)
    log.info('Written %s', fonts_css_path)


if __name__ == '__main__':
    logging.basicConfig(level=logging.INFO, format='%(message)s')
    download_web_assets()
